### ISSUE TITLE
Избыточность?

### ISSUE THREAD

**Issue by gluxix** [zakharovadaria/vocabulary_generator#1]
Я питон вообще не знаю, но можно ли сократить функцию:

https://github.com/zakharovadaria/vocabulary_generator/blob/58b92242ad51ec3e5e09474b22b1d8378995bf37/src/vocabulary_generator/core.py#L8-L15

например вот так:
```python
def get_all_words_in_text(text: str) -> List[str]:
    return text.strip().lower().split(' ')
```
 в этом случае (если так можно), результат будет одинаковым, и читается лучше, понятно что происходит со строкой последовательно.

Это же касается некоторых других функций.

**Comment by gluxix** [comment]
В приведенном примере есть смысл сократить, а вот например для метода:

https://github.com/zakharovadaria/vocabulary_generator/blob/58b92242ad51ec3e5e09474b22b1d8378995bf37/src/vocabulary_generator/core.py#L43-L49

было бы уже в минус читаемости, хотя в одну строчку тоже можно написать, но будет не красиво и сложней читать.

**Comment by zakharovadaria** [comment]
В первом случае, если на ввод послать пустую строку (например,  "   "), то вместо пустого массива будет возвращаться массив с одним элементом - пустой строкой, хотя пустая строка не является "словом". Для всех остальных случаев будет работать корректно.

Во втором, я бы оставила как есть, потому что здесь понятно за что отвечает каждая строка кода, если сократить может быть не совсем ясно.

**Comment by gluxix** [comment]
> Во втором, я бы оставила как есть, потому что здесь понятно за что отвечает каждая строка кода, если сократить может быть не совсем ясно.

Ну да, я про второй случай как раз сказал, что там наоборот хорошо, сокращение только ухудшит :)
