### ISSUE TITLE
Подсчет частотности слов в тексте

### ISSUE THREAD

**Issue by gluxix** [zakharovadaria/vocabulary_generator#2]
Может быть добавить метод подсчета частотности слов, например:
`one two two three three three` => `{ 'one': 1, 'two': 2, 'three': 3 }`.

Типа такого
```python
from collections import Counter

# ...

def get_words_frequency(words: List[str]):
    counter = Counter()
    for word in words:
        counter[word] += 1
    return counter
```

**Comment by odryfox** [comment]
@gluxix можно воспользоваться конструктором Counter
`
>>> from collections import Counter
>>> words = ["foo", "bar", "foo", "boo"]
>>> Counter(words)
Counter({'foo': 2, 'bar': 1, 'boo': 1})
`

**Comment by gluxix** [comment]
@odryfox А Counter() List может принять? Или массив нужен?

```python
from collections import Counter

# ...

def get_words_frequency(words: List[str]):
    return Counter(words)
```

**Comment by odryfox** [comment]
@gluxix Counter может принять все, по чему можно проитерироваться.

List это всего лишь аннотация типа list (массив).
```python
>>> type([])
<class 'list'>
```
