### ISSUE TITLE
Ошибка в названии метода или его логике

### ISSUE THREAD

**Issue by gluxix** [zakharovadaria/vocabulary_generator#3]
https://github.com/zakharovadaria/vocabulary_generator/blob/58b92242ad51ec3e5e09474b22b1d8378995bf37/src/vocabulary_generator/core.py#L43-L49

Этот метод по названию должен вернуть все слова в первоначальной форме, но метод возвращает Set, то есть он вернет меньше чем ВСЕ слова.

Например: `do done` => ['do']. Хотя правильней было бы вернуть ['do', 'do']. Если нужно будет, то уже обрезать методом, который возвращает только уникальные слова, а так этот список можно использовать для подсчета частотности слов.

**Comment by zakharovadaria** [comment]
Верно, нужно переименовать в вернуть все уникальные слова в начальной форме

**Comment by gluxix** [comment]
> Верно, нужно переименовать в вернуть все уникальные слова в начальной форме

@zakharovadaria а у тебя такой метод уже есть, тут лучше не переименовать, а возвращать не "уникальные", а как получится. Тогда результат работы этой функции можно использовать для подсчета ["частотности"](https://github.com/zakharovadaria/vocabulary_generator/issues/2) слов в тексте.

**Comment by zakharovadaria** [comment]
Разрешилось после создания функции подсчета частотности слов [commit](https://github.com/zakharovadaria/vocabulary_generator/commit/638c35b8a12e67bb09b281ed2aa4f3804f8474a8)
